In [56]:
!pip install pandas numpy openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: numpy in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: openpyxl in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (2.0.52)
Requirement already satisfied: pymysql in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.14.1)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: C:\Users\HP\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [57]:
#step import req libraries 
import pandas as pd 
import numpy as np

In [58]:
#step import the dataset 
df = pd.read_excel("Ecommerce_Unclean_Project.xlsx")
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [59]:
#step: view the information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    object
 1   Order_Date     524 non-null    object
 2   Customer_Name  524 non-null    object
 3   Email          524 non-null    object
 4   Phone          502 non-null    float64
 5   City           524 non-null    object
 6   State          524 non-null    object
 7   Product        524 non-null    object
 8   Category       524 non-null    object
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    object
 13  Order_Status   524 non-null    object
 14  Delivery_Date  503 non-null    object
dtypes: float64(3), object(12)
memory usage: 61.5+ KB

In [60]:
# statistical summary 
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [61]:
# dataset shape
df.shape

(524, 15)

In [62]:
# step : check the missing values 
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [63]:
df.duplicated().sum()

np.int64(11)

In [64]:
# remove duplicate record
df.drop_duplicates(inplace=True)

In [65]:
#replace invalid values 
#replace common invalid values with NaN 

df.replace(['N/A','NULL',' '],np.nan,inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_14016\932338053.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['N/A','NULL',' '],np.nan,inplace=True)

In [66]:
# remove the blank
df = df.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)

In [67]:
# Standard Text Format
# Convert Text into Proper Case.
df['Category'] = df['Category'].str.title()
df['City'] = df['City'].str.title()
df['Payment_Mode'] = df['Payment_Mode'].str.title()
df['Product'] = df['Product'].str.title()
df['State'] = df['State'].str.title()

In [68]:
# Validate Email Address
# keep only valid records

df = df[df['Email'].str.contains('@',na=False)]

In [69]:
# convert data columnsabs
df['Order_Date'] = pd.to_datetime(df['Order_Date'],errors='coerce')
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'],errors='coerce')

C:\Users\HP\AppData\Local\Temp\ipykernel_14016\4223745311.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date'] = pd.to_datetime(df['Order_Date'],errors='coerce')

In [70]:
# convert numeric columns

cols = ['Qty','Unit_Price','Discount']

for c in cols:
    df[c] = pd.to_numeric(df[c],errors='coerce')

In [92]:
df.head(20)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Total_sales,Net_sales,Profit,Order_month,Order_year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,Upi,Pending,2025-03-07,7996.0,7996.00,1599.20,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,2025-09-02,24995.0,19996.00,3999.20,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,Cod,Returned,2025-08-05,5997.0,5697.15,1139.43,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,2025-02-10,1497.0,1197.60,239.52,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-17,39996.0,39996.00,7999.20,February,2025.0,Monday
7,ORD1009,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,...,0.0,Wallet,Pending,NaT,2998.0,2998.00,599.60,NaN,NaN,NaN
8,ORD1010,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,...,0.0,Netbanking,Delivered,2025-04-10,NaN,NaN,NaN,April,2025.0,Thursday
9,ORD1011,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,Cod,Pending,2025-01-11,2997.0,2997.00,599.40,January,2025.0,Saturday
10,ORD1012,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,...,5.0,Cod,Cancelled,2025-09-03,2997.0,2847.15,569.43,March,2025.0,Monday
13,ORD1015,2025-03-17,Rohit,rohit6@gmail.com,9643353842.0,Lucknow,Up,Bottle,Home,5.0,...,5.0,Card,Returned,2025-03-17,NaN,NaN,NaN,March,2025.0,Monday
14,ORD1016,2025-03-31,Sneha,sneha86@gmail.com,9125254427.0,Pune,Maharashtra,Laptop,Electronics,3.0,...,20.0,Netbanking,Pending,2025-09-04,14997.0,11997.60,2399.52,March,2025.0,Monday
15,ORD1017,2025-01-12,Vikas,vikas12@gmail.com,9498228945.0,Jaipur,Rajasthan,Watch,Fashion,1.0,...,10.0,Netbanking,Pending,2025-01-12,4999.0,4499.10,899.82,January,2025.0,Sunday
16,ORD1018,NaT,Amit,amit96@gmail.com,9124086971.0,Mumbai,Maharashtra,Shoes,Fashion,2.0,...,5.0,Wallet,Delivered,NaT,9998.0,9498.10,1899.62,NaN,NaN,NaN
17,ORD1019,2025-03-06,Vikas,vikas20@gmail.com,9524467082.0,Bengaluru,Karnataka,Chair,Furniture,3.0,...,0.0,Cod,Returned,2025-03-06,4497.0,4497.00,899.40,March,2025.0,Thursday
18,ORD1020,2025-03-15,Rahul,rahul90@gmail.com,9106119129.0,Pune,Maharashtra,Watch,Fashion,3.0,...,0.0,Upi,Returned,2025-03-15,2997.0,2997.00,599.40,March,2025.0,Saturday
19,ORD1021,2025-01-27,Priya,priya82@gmail.com,9583849937.0,Pune,Maharashtra,Chair,Furniture,3.0,...,5.0,Upi,Cancelled,2025-02-02,NaN,NaN,NaN,January,2025.0,Monday
21,ORD1023,2025-04-27,Neha,neha70@gmail.com,9133995118.0,Mumbai,Maharashtra,Shoes,Fashion,1.0,...,5.0,Cod,Pending,2025-01-05,499.0,474.05,94.81,April,2025.0,Sunday
22,ORD1024,2025-06-29,Rohit,rohit60@gmail.com,9633404088.0,Bengaluru,Karnataka,Mouse,Electronics,3.0,...,15.0,Card,Cancelled,2025-08-07,NaN,NaN,NaN,June,2025.0,Sunday
24,ORD1026,2025-04-05,Sneha,sneha71@gmail.com,9967773139.0,Bengaluru,Karnataka,Bottle,Home,4.0,...,10.0,Wallet,Returned,2025-08-04,39996.0,35996.40,7199.28,April,2025.0,Saturday
26,ORD1028,2025-06-05,Amit,amit15@gmail.com,9853264878.0,Lucknow,Up,Watch,Fashion,3.0,...,0.0,Netbanking,Cancelled,2025-09-06,14997.0,14997.00,2999.40,June,2025.0,Thursday

In [72]:
# record invalid quantity 
# remoce record hoaving negative or zero 
df = df[df['Qty']>0]

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       374 non-null    object
 1   Order_Date     333 non-null    datetime64[ns]
 2   Customer_Name  380 non-null    object
 3   Email          380 non-null    object
 4   Phone          366 non-null    float64
 5   City           380 non-null    object
 6   State          380 non-null    object
 7   Product        380 non-null    object
 8   Category       380 non-null    object
 9   Qty            380 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       275 non-null    float64
 12  Payment_Mode   380 non-null    object
 13  Order_Status   380 non-null    object
 14  Delivery_Date  135 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(4), object(9)
memory usage: 47.5+ KB

In [74]:
df['Discount'] = pd.to_numeric(df['Discount'],errors='coerce').fillna(0)
df['Phone'] = df['Phone'].fillna('Unknown')
df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

In [77]:
# feacture engineering 
# total sales 
# net sales
df['Total_sales'] = df['Unit_Price']*df['Qty']
df['Net_sales'] = df["Total_sales"]-(df['Total_sales']*df['Discount']/100)

In [80]:
# 20% profit 
df['Profit'] = df['Net_sales']*20/100

In [82]:
#order month
df["Order_month"] = df['Order_Date'].dt.month_name()

In [91]:
#order Year
# weekday
df['Order_year'] = df['Order_Date'].dt.year
df['Weekday'] = df['Order_Date'].dt.day_name()

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       374 non-null    object
 1   Order_Date     333 non-null    datetime64[ns]
 2   Customer_Name  380 non-null    object
 3   Email          380 non-null    object
 4   Phone          380 non-null    object
 5   City           380 non-null    object
 6   State          380 non-null    object
 7   Product        380 non-null    object
 8   Category       380 non-null    object
 9   Qty            380 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       380 non-null    float64
 12  Payment_Mode   380 non-null    object
 13  Order_Status   380 non-null    object
 14  Delivery_Date  348 non-null    datetime64[ns]
 15  Total_sales    343 non-null    float64
 16  Net_sales      343 non-null    float64
 17  Profit         343 non-null    float64
 18  Order_month    333 non-null    object
 19  Order_year     333 non-null    float64
 20  Weekday        333 non-null    object
dtypes: datetime64[ns](2), float64(7), object(12)
memory usage: 65.3+ KB

In [94]:
df.isnull().sum()

Order_ID          6
Order_Date       47
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       37
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date    32
Total_sales      37
Net_sales        37
Profit           37
Order_month      47
Order_year       47
Weekday          47
dtype: int64

In [95]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Total_sales,Net_sales,Profit,Order_year
count,333,380.000000,343.000000,380.000000,348,343.000000,343.000000,343.000000,333.0
mean,2025-04-02 17:35:08.108108032,3.328947,3252.352770,7.802632,2025-05-01 04:12:24.827586304,11103.664723,10249.073324,2049.814665,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.000000,2025-01-02 00:00:00,499.000000,399.200000,79.840000,2025.0
25%,2025-02-14 00:00:00,2.000000,999.000000,0.000000,2025-02-16 18:00:00,2599.000000,2398.400000,479.680000,2025.0
50%,2025-04-05 00:00:00,3.000000,1999.000000,5.000000,2025-04-19 00:00:00,5997.000000,5996.000000,1199.200000,2025.0
75%,2025-05-16 00:00:00,5.000000,4999.000000,15.000000,2025-06-18 00:00:00,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,20.000000,2025-12-06 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.458196,3026.092014,7.881075,NaN,12194.528486,11506.169779,2301.233956,0.0

In [96]:
# Export clean data 
df.to_csv('Clean_Ecommerce.csv',index=False)

In [103]:
#import data into mysql 
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:123456@localhost/ecommerce')

In [104]:
#export dataframe to mysql
df.to_sql(
    name='orders',
    con = engine,
    if_exists='replace',
    index=False
)

380

In [105]:
df.shape

(380, 21)